name: 'Sonarcloud Check Status Action'
description: 'Checks the status of a SonarCloud project'
branding:
  icon: cloud
  color: orange
inputs:
  url:
    description: 'url of sonarcloud'
    required: false
    default: 'https://sonarcloud.io'
  org:
    description: 'Github Organization'
    required: false
  repo:
    description: 'Github Repo'
    required: false
  branch:
    description: 'Branch to check status. Defaults the current ref.'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
